# crear_tabla_productos.py
# Tablas relacionales sin imágenes, con FK simbólicas (sin ON DELETE)

import os
from databricks import sql as dbsql
from dotenv import load_dotenv

load_dotenv()

DATABRICKS_HOST  = os.getenv("DATABRICKS_HOST", "").replace("https://", "").replace("http://", "")
DBSQL_HTTP_PATH  = os.getenv("DBSQL_HTTP_PATH", "")
DATABRICKS_TOKEN = os.getenv("DATABRICKS_TOKEN", "")
DBX_CATALOG      = os.getenv("DBX_CATALOG", "workspace")
DBX_SCHEMA       = os.getenv("DBX_SCHEMA", "default")

def connect():
    if not (DATABRICKS_HOST and DBSQL_HTTP_PATH and DATABRICKS_TOKEN):
        raise RuntimeError("Faltan DATABRICKS_HOST, DBSQL_HTTP_PATH, DATABRICKS_TOKEN")
    return dbsql.connect(
        server_hostname=DATABRICKS_HOST,
        http_path=DBSQL_HTTP_PATH,
        access_token=DATABRICKS_TOKEN,
    )

def run(cur, stmt: str):
    for s in [x.strip() for x in stmt.split(";") if x.strip()]:
        cur.execute(s)

SQL_BOOTSTRAP = f"""
CREATE CATALOG IF NOT EXISTS {DBX_CATALOG};
USE CATALOG {DBX_CATALOG};
CREATE SCHEMA IF NOT EXISTS {DBX_SCHEMA};
USE {DBX_CATALOG}.{DBX_SCHEMA};
"""

SQL_CREATE_TABLES = """
CREATE TABLE IF NOT EXISTS clientes (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
  telegram_user_id  BIGINT,
  nombre            STRING,
  telefono          STRING,
  email             STRING,
  direccion         STRING,
  created_at        TIMESTAMP,
  CONSTRAINT pk_clientes PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS descripcion_productos (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
  nombre        STRING NOT NULL,
  descripcion   STRING,
  categoria     STRING,
  unidad        STRING,
  activo        BOOLEAN,
  created_at    TIMESTAMP,
  CONSTRAINT pk_desc PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS inventario (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
  producto_id   BIGINT NOT NULL,
  sku           STRING,
  precio_cop    INT NOT NULL,
  stock         INT NOT NULL,
  ubicacion     STRING,
  updated_at    TIMESTAMP,
  CONSTRAINT pk_inv PRIMARY KEY (id)
  -- FOREIGN KEY (producto_id) REFERENCES descripcion_productos(id)  ← simbólica
);

CREATE TABLE IF NOT EXISTS pedidos (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
  cliente_id  BIGINT NOT NULL,
  estado      STRING,
  total_cop   INT,
  items       ARRAY<STRUCT<
                 inventario_id BIGINT,
                 cantidad      INT,
                 precio_cop    INT,
                 nombre        STRING
               >>,
  notas       STRING,
  created_at  TIMESTAMP,
  CONSTRAINT pk_pedidos PRIMARY KEY (id)
  -- FOREIGN KEY (cliente_id) REFERENCES clientes(id)  ← simbólica
);

CREATE OR REPLACE VIEW v_productos AS
SELECT
  inv.id            AS inventario_id,
  dp.id             AS producto_id,
  dp.nombre,
  dp.descripcion,
  dp.categoria,
  dp.unidad,
  inv.precio_cop,
  inv.stock
FROM inventario inv
JOIN descripcion_productos dp
  ON inv.producto_id = dp.id
WHERE dp.activo = TRUE OR dp.activo IS NULL;
"""

SQL_SEEDS = """
INSERT INTO descripcion_productos (nombre, descripcion, categoria, unidad, activo)
VALUES
('Papel higiénico 4 rollos', 'Papel doble hoja suave', 'Aseo', 'paquete', TRUE),
('Shampoo 400 ml', 'Shampoo para uso diario', 'Aseo personal', 'unidad', TRUE),
('Jabón de baño 90 g', 'Jabón en barra neutro', 'Aseo personal', 'unidad', TRUE),
('Toallas de mano (par)', 'Toallas 100% algodón', 'Hogar', 'par', TRUE)
;

INSERT INTO inventario (producto_id, sku, precio_cop, stock, ubicacion)
VALUES
(1, 'PAP-4R', 12000, 30, 'B1-E1'),
(2, 'SHP-400', 18000, 25, 'B1-E2'),
(3, 'JBN-090', 3500,  50, 'B1-E3'),
(4, 'TLL-PAR', 22000, 15, 'B2-E1')
;

INSERT INTO clientes (telegram_user_id, nombre, telefono, email, direccion)
VALUES
(1410584383, 'Jeison Trujillo', '3001112233', 'jeison@example.com', 'Bogotá'),
(1410584384, 'María Pérez', '3002223344', 'maria.perez@example.com', 'Medellín'),
(1410584385, 'Carlos Gómez', '3003334455', 'carlos.gomez@example.com', 'Cali')
;
"""

def main():
    print(f"Conectando a Databricks SQL ({DATABRICKS_HOST})...")
    with connect() as conn, conn.cursor() as cur:
        print("→ Creando/seleccionando catálogo y esquema…")
        run(cur, SQL_BOOTSTRAP)

        print("→ Creando tablas y vista (FK simbólicas)…")
        run(cur, SQL_CREATE_TABLES)

        print("→ Insertando datos mínimos…")
        run(cur, SQL_SEEDS)

        print("→ Verificando v_productos…")
        cur.execute("SELECT inventario_id, nombre, precio_cop, stock FROM v_productos ORDER BY inventario_id LIMIT 10")
        rows = cur.fetchall()
        for r in rows:
            print(f"   #{r[0]} {r[1]} — ${int(r[2]):,} (stock: {r[3]})".replace(",", "."))

    print("✅ Listo. Esquema relacional (FK simbólicas) + semillas creadas.")

if __name__ == "__main__":
    main()
